### PR TITLE
Added Cyberduck

### PR DESCRIPTION
**Pull request by Fydon**
Thank you for komorebi. I'm not sure if I've used the best float identifier, but its a start. Is there any documentation or description of what kinds of float identifiers and what the options mean?

- [x] I have formatted `applications.yaml` with `komorebic fmt-asc`.

### CODE REVIEW

**Comment by Fydon** [comment]
Should I add `matching_strategy` to `float_identifiers` as well?

**Review by sitiom — CHANGES_REQUESTED** [review]
See https://github.com/LGUG2Z/komorebi-application-specific-configuration/pull/63#pullrequestreview-1745794488

**Comment by Fydon** [comment]
Thank you. The same class is applied across all windows for Cyberduck. Are there any other options I have?

Both [WinListener](https://www.nirsoft.net/utils/winlister.html) and the Window Spy tool you use seem to imply that windows can be linked back to an exe file. Is there a reason for not using the float identifier with the identifier?

image

**Comment by sitiom** [comment]
> Both [WinListener](https://www.nirsoft.net/utils/winlister.html) and the Window Spy tool you use seem to imply that windows can be linked back to an exe file. Is there a reason for not using the float identifier with the identifier?

Yes, but as mentioned in https://github.com/LGUG2Z/komorebi-application-specific-configuration/pull/63#pullrequestreview-1745794488, `float_identifers` would match for all windows due to komorebi limitations. You can see this with the generated AHK rules:
image

As you can see here, float rules are not yet associated with the identifier.

> Are there any other options I have?

As for now, I suggest removing the `float_identifiers` for now until the issue is resolved on the komorebi side.

**Comment by Fydon** [comment]
Okay. Thank you for the clarification. I'll close this for now until the floating windows are able to be identified.

**Pull request closed without merging**
