### PR TITLE
fix(steambeta;signal): Fixed Signal.exe case sensitivity. Only the main Steam window will now get managed

### PR DESCRIPTION
**Pull request by cirehtheterrible**
Makes only the main Steam window tile. Also fixes a quirk, where the "Your friend is now playing..." window would re-tile the screen.
Fixes Signal.exe not closing properly.

- [x] I have formatted `applications.yaml` with `komorebic fmt-asc`.

### CODE REVIEW

**Comment by LGUG2Z** [comment]
Thanks for this @cirehtheterrible! I actually just pushed a commit for the Steam Beta issue before checking this PR so that can be dropped from here. As for Signal, depending on how it is installed it can have either an upper or lowercase S; for this I think the best thing we can do is just duplicate the entry with the other case. If you can make these changes let's get this PR merged in today. 🤞

**Comment by cirehtheterrible** [comment]
Should I remove the Steam tiling behavior as well? I don't know if you have any guidelines to follow when making the custom settings, but, to me at least, it felt more natural to only have the main steam window tile, while the Settings, Logging in and "Shutting down" windows would float.

**Review by sitiom — CHANGES_REQUESTED** [review]
> Should I remove the Steam tiling behavior as well? I don't know if you have any guidelines to follow when making the custom settings, but, to me at least, it felt more natural to only have the main steam window tile, while the Settings, Logging in and "Shutting down" windows would float.

Generally, non-resizable windows should float. In this case, it would make sense to float the other popups like settings, but using the "Steam" window title as the identifier is too ambiguous.

**Comment by LGUG2Z** [comment]
```
- name: Steam Beta - float_rule
  identifier:
    kind: title
    id: Steam
  options:
  - force
  float_identifiers:
  - kind: exe
    id: steamwebhelper.exe
```

You can remove this from the PR as it's now covered [here](https://github.com/LGUG2Z/komorebi-application-specific-configuration/commit/0415d309a2885bfdba7016de94faec9e0363cf09), then you just need to duplicate the Signal entry for the uppercase exe name 👌

**Comment by sitiom** [comment]
> As for Signal, depending on how it is installed it can have either an upper or lowercase

@LGUG2Z I'm guessing you installed Signal through Scoop 😅. Even inside the installer, `Signal.exe` is capital case. This should be fixed upstream to the Extras bucket (which I have access to: https://github.com/ScoopInstaller/Extras/commit/d9f9efbbfd15b91001d8099bc7a07b19304ae76d).

**Comment by cirehtheterrible** [comment]
> 
May I ask what is the correct way to implement this? Is there a way to pair the `title` identifier to a specific .exe? I settled on this approach because even though the "Steam Settings" and "Steam Controller Configs" windows have "Steam" in them, they didn't get tiled.

**Comment by sitiom** [comment]
> Is there a way to pair the `title` identifier to a specific .exe?

There isn't such functionality for now. I recommend opening an issue on the komorebi repo for that, though. It's a good idea.

**Pull request closed without merging**
